title: Alexandra Dobre
logo: /assets/img/headshot_circle.png
description: |
  <p><a href="https://www.linkedin.com/in/alexandradobre/">LinkedIn Profile</a></p>
  <p><a href="/assets/img/Dobre_CV_June2025.pdf">Resume</a></p>
  <p><a href="https://papers.ssrn.com/sol3/cf_dev/AbsByAuth.cfm?per_id=4813546">Social Science Research Network (SSRN) Page</a></p>
#show_downloads: true
theme: jekyll-theme-minimal
