title: Alexandra Dobre
logo: /assets/img/headshot_circle.png
description: |
  [LinkedIn Profile](https://www.linkedin.com/in/alexandradobre/)
  [Resume](/assets/Dobre_CV_June2025.pdf) # Assuming you'll place your resume in the assets folder
  [View My GitHub Profile](https://github.com/dobre-alexandra)
#show_downloads: true
theme: jekyll-theme-minimal
